name: Publish release
on: 
  push:
    tags-ignore:
     - 'v*-beta*'
     - 'v*-alpha*'
  workflow_dispatch:
permissions:
  contents: read

jobs:
   upload-normal:
    name: Create non-optimized datapack
    runs-on: ubuntu-latest
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f
       with:
         egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

     - name: Clone repository
       uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
       with:
         fetch-depth: 0
     - name: Check commands
       uses: mcbeet/check-commands@03cff79228a0a50fe6856becd7972112e326e922
       with:
          source: .
          minecraft: 1.18
     - name: Check JSON
       uses: ocular-d/json-linter@7d3716a34bcd6fcc5b3b38141a21b9e02da6531d
     - name: Upload artifact
       uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
       with:
         path: |
             assets/
             data/
             pack.mcmeta
             pack.png
         name: end-crystal-datapack v1.0.0

         
   upload-optimized-datapack:
    permissions:
      actions: read  # for ComunidadAylas/PackSquash-action to get latest artifact
    name: Optimize datapack
    runs-on: ubuntu-latest
    needs: upload-normal
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f
       with:
         egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

     - name: Download normal pack
       uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
       with:
         name: end-crystal-datapack v1.0.0
         path: ./
     - name: Run PackSquash
       uses: ComunidadAylas/PackSquash-action@cdeba7365a1491b436b1a9c381d63b5ee6c27f2e
       with:
          path: ./
          token: ${{ secrets.GITHUB_TOKEN }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
          artifact_name: 'optimized-end-crystal-datapack v1.0.0'
          never_store_squash_times: true

   create-release:
     permissions:
       contents: write  # for softprops/action-gh-release to create GitHub release
       issues: read  # for heinrichreimer/github-changelog-generator-action to fetch issues and labels
       pull-requests: read  # for heinrichreimer/github-changelog-generator-action to fetch PRs and labels
     name: Create release
     needs: [upload-normal,upload-optimized-datapack]
     runs-on: ubuntu-latest
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f
         with:
           egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

       - name: Checkout repo
         uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
         with:
           token: ${{ secrets.GH_TOKEN }}
       - name: Generate release changelog
         uses: heinrichreimer/github-changelog-generator-action@6653241a44afb59146f719f322005de49a5c3b38
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           dateFormat: '%m/%d/%Y'
       - name: Download normal pack
         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
         with:
           name: end-crystal-datapack v1.0.0
       - name: Zip pack
         run: zip 'end-crystal-datapack v1.0.0' -r data pack.mcmeta # pack.png
       - name: Delete datapack
         run: rm -r data pack.mcmeta # pack.png  
       - name: Download optimized pack
         uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
         with:
           name: optimized-end-crystal-datapack v1.0.0
       - name: Zip optimized pack
         run: |
           unzip -f pack.zip
           zip -r 'optimized-end-crystal-datapack v1.0.0' . -i data pack.mcmeta 
       - name: Release
         uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
         with:
           files: |
             *.zip
           body_path: CHANGELOG.md
       - name: Commit changes
         run: |
            echo ${GITHUB_REF#refs/*/}
            git config --local user.name "actions-user"
            git config --local user.email "action@github.com"
            git add CHANGELOG.md
            git commit -m "[ci skip] Updated CHANGELOG.md for ${{ github.ref }}"
            git push origin HEAD:master
            
